name: mldl-project
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.0
  - absl-py=0.13.0
  - aiohttp=3.7.4.post0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=21.2.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - click=8.0.1
  - cryptography=3.4.7
  - cycler=0.10.0
  - dataclasses=0.8
  - freetype=2.10.4
  - gast=0.3.3
  - giflib=5.2.1
  - google-auth=1.30.2
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpc-cpp=1.37.1
  - grpcio=1.37.1
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - importlib-metadata=4.5.0
  - jbig=2.1
  - joblib=1.0.1
  - jpeg=9d
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.19.1
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libcxx=11.1.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libssh2=1.9.0
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - multidict=5.1.0
  - ncurses=6.2
  - numpy=1.19.5
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - pandas=1.2.4
  - patsy=0.5.1
  - pillow=8.2.0
  - pip=21.1.2
  - plotly=4.14.3
  - protobuf=3.15.8
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.9.5
  - python-dateutil=2.8.1
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytz=2021.1
  - pyu2f=0.1.5
  - re2=2021.04.01
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - retrying=1.3.3
  - rsa=4.7.2
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - setuptools=49.6.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.4.0
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.60.0
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - urllib3=1.26.5
  - werkzeug=2.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yarl=1.6.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - pip-chill==1.0.1
    - tensorflow-addons==0.13.0
    - typeguard==2.12.0
prefix: /Users/mircodemarchi/anaconda3/envs/mldl-project
